FROM docker.io/library/rust:slim AS builder

WORKDIR /fir
COPY foxhole foxhole
COPY includes includes
COPY native native

WORKDIR /fir/native
RUN cargo build --release --bin fic


FROM gcr.io/distroless/cc-debian13:latest

COPY --from=builder /fir/native/target/release/fic /usr/local/bin/fic
COPY LICENSE /LICENSE

ENTRYPOINT ["fic"]
